CREATE DATABASE application;
CREATE USER superuser WITH ENCRYPTED PASSWORD 'superpassword';
GRANT ALL PRIVILEGES ON DATABASE application TO superuser;

CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE');
CREATE TABLE IF NOT EXISTS public.users (
   id serial PRIMARY KEY,
   SURNAME VARCHAR (50) NOT NULL,
   FIRSTNAME VARCHAR (50) NOT NULL,
   GENDER gender_type NOT NULL,
   BIRTHDATE TIMESTAMP NOT NULL,
   EMAIL VARCHAR (100) UNIQUE NOT NULL,
   USERNAME VARCHAR (50) UNIQUE NOT NULL,
   PASSWORD VARCHAR (110) NOT NULL,
   COMPROMISED BOOLEAN NOT NULL DEFAULT FALSE,
   VERSION INTEGER NOT NULL,
   ATTEMPTS INTEGER NOT NULL DEFAULT 0
);
